on: [push]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    name: A job to test with fold server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Test
        id: fold
        uses: ognerezov/fold-test-node@main
        with:
          context: .
          dir: '/fold'
          work-dir: '/'
          test: 'npm install && npm run test'
