on: [push]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    name: A job to test with mock server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Test
        id: fold
        uses: ognerezov/fold-test-node@main
        with:
          context: .
          dir: '/mock'
#          work_dir: '/'
          test: 'npm run test'
