on: [push]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    name: A job to test with mock server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Test
        id: fold
        uses: ognerezov/fold-test-node@0.3
        with:
          dir: '/github/workspace/mock'
          work_dir: '/github/workspace'
          test: 'npm run test'
